### ISSUE TITLE
Refactor rename error - java.io.IOException: Cannot rename x to y

### ISSUE THREAD

**Issue by razvan-panda** [Atsky/haskell-idea-plugin#111]
On some files (in my case, seems to only happen to all files placed in `tests` folder except one of them: Spec.hs) when performing refactor rename:

![](http://i.imgur.com/i97HELi.png)

the following error is thrown:

    java.io.IOException: Cannot rename 'D:\Codewars\Haskell\tests\CodewarsKataNthRootSpec.hs' to 'NthRootSpec.hs'

![](http://i.imgur.com/d2w5CLD.png)

**Comment by razvan-panda** [comment]
My bad, it was just `cabal repl` locking the files:

![](http://i.imgur.com/voJinJD.png)

**Comment by nanastya** [comment]
Also the reason may be an open terminal in php storm (when you are in the directory of the file you want to rename). This comment is for as inattentive users as me =)
