### ISSUE TITLE
remote-debugger-0.2.2 : failed during the building phase.

### ISSUE THREAD

**Issue by DekwoKybon** [atsky/haskell-idea-plugin#121]
When I try to install the remote-debugger using 'cabal install remote-debugger' I get following errors:

src/DebuggerImpl.hs:95:77:
    Not in scope: data constructor ‘PackageArg’

src/DebuggerImpl.hs:95:94:
    Not in scope: data constructor ‘ModRenaming’

I'm using  ghc version: 7.8.4 and cabal version:  1.22.1.1

**Comment by fshp** [comment]
@DekwoKybon try use ghc >= 7.10
It depends on AMP.

**Comment by stefan-schweiger** [comment]
My installation also failes, but with a slighly different error (using ghc: 8.0.1 and cabal: 1.24.0.0) https://github.com/octomarat/HaskellDebugger/issues/5
