### ISSUE TITLE
Plugin attempts to open a non-existent file

### ISSUE THREAD

**Issue by nikomi** [Atsky/haskell-idea-plugin#46]
Haskell plugin 0.3.0 pops up an error about a non-existent file every few seconds:

ghc-modi failed
NG /Library/Frameworks/GHC.framework/Versions/7.6.3-x86_64/usr/lib/ghc-7.6.3/platformConstants: openFile: does not exist (No such file or directory)

I'm already using GHC 7.8, so the attempt to read a GHC 7.6 file will not work - and I don't use the platform, so the path would be incorrect anyway. 

Unluckily this appears to be hard-coded, at least I have not found a configuration option to avoid this problem.

This message does not seem to appear in the log, so I have attached a screen shot.

![idea](https://cloud.githubusercontent.com/assets/6458404/3853638/07f4688c-1ec9-11e4-9b27-99154ad2e50c.png)

**Comment by Atsky** [comment]
This is a problem is ghc-modi utility. Reinstalling it should help.
