### ISSUE TITLE
exceptions due to missing ~/Library/Haskell/bin directory

### ISSUE THREAD

**Issue by simonmichael** [Atsky/haskell-idea-plugin#51]
I upgraded to 0.3.x from the previous 0.2.x release. I got lots of exceptions as it tried to run ~/Library/Haskell/bin/ghc-modi . It seems happy after sym-linking ~/Library/Haskell to ~/.cabal and restarting the IDE.

**Comment by Atsky** [comment]
Now you can set path to ghc-modi in Settings
