### ISSUE TITLE
java.lang.NullPointerException when compiling

### ISSUE THREAD

**Issue by jorgef** [Atsky/haskell-idea-plugin#56]
I am new to Haskell, I just installed the plugin for intellij Idea (community edition) and created a new Haskell module (called 'test2').
When trying to compile it, I got the following error:

Error:Module 'test2' production: java.lang.NullPointerException

![haskell-error](https://cloud.githubusercontent.com/assets/941277/4657196/26743204-54e5-11e4-9468-20e6715b473f.PNG)

Screencast: https://jetbrains1.viewscreencasts.com/embed/62aeeac6265a4d2393395154eaaed6d2

**Comment by emomarjan** [comment]
i receive the same error in intellij idea
