### ISSUE TITLE
Kotlin error trying to open .cabal (Haskell) project

### ISSUE THREAD

**Issue by Atsky** [Atsky/haskell-idea-plugin#64]
Steps to reproduce in IDEA 14:
 git clone git@github.com:leksah/leksah.git
 install Haskell plugin for IDEA
 File -> Import Project -> look for leksah.cabal
 Click OK

a popup appears with the following message:

Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/KObject

**Comment by ianbamforth** [comment]
Same issue here.
