### ISSUE TITLE
ghc-modi failed - hGetContents: invalid argument

### ISSUE THREAD

**Issue by cnsgcu** [Atsky/haskell-idea-plugin#75]
Hi,
I am having the following error with the plug-in on IntelliJ version 14.

Error:
ghc-modi failed
ghc-modi failed with error: NG BUG: GMEIOException /Users/ME/IdeaProjects/PROJECT_NAME/dist/setup-config: hGetContents: invalid argument (invalid byte sequence)

System Info:
OSX 10.10
cabal-install version 1.22.0.0
ghc-7.8.3

Thanks,

**Comment by Atsky** [comment]
Hi, 
What version of ghc-mod are you using? Try to install new version.

**Comment by cnsgcu** [comment]
Thank you for your help!

**Comment by karlicoss** [comment]
@cnsgcu So, why did you close it? :)

**Comment by karlicoss** [comment]
The issue seems to be nod in the plugin, bat rather in ghc-mod. https://github.com/kazu-yamamoto/ghc-mod/issues/417
