### ISSUE TITLE
Unable to find way to disable ghc-modi

### ISSUE THREAD

**Issue by ianbamforth** [Atsky/haskell-idea-plugin#78]
Error message says ghc-modi failed with error: 

NG_BUG: GMEIOException /some/path/setup-config: hGetContents: invalid argument (invalid byte sequence).  You can disable ghc-modi in Settings | Haskell

It helpfully links to the Settings / Haskell dialog, but there's no option there to disable ghc-modi.

IDEA 14.0.3, haskell-idea-plugin 0.4.1, Ubuntu 14.04

**Comment by Atsky** [comment]
To disable ghc-mod uncheck "Use ghc-mod automatic check (turn off if you have problems with ghc-mod)"

**Comment by Atsky** [comment]
Also install new version of ghc-mod this should resolve this problem see #75
