### ISSUE TITLE
Provide default configuration for running Haskell programs

### ISSUE THREAD

**Issue by apennebaker-ni** [Atsky/haskell-idea-plugin#79]
When I click Run... I expect IntelliJ to run my Haskell programs / test suites. Could this plugin please come with a default configuration for this?

**Comment by Atsky** [comment]
You can right click in editor when some Haskell file is opened and select Run or press Ctrl+Shift + F10 in editor.

**Comment by apennebaker-ni** [comment]
When I select Run, I don't see a menu with relevant ways to run my Haskell programs or test suites. I just see the generic IntelliJ *please configure me* dialog.

**Comment by Atsky** [comment]
I mean context menu in editor.
![screen shot 2015-02-12 at 10 25 03](https://cloud.githubusercontent.com/assets/145728/6164666/8455bb44-b2a1-11e4-8330-b4ea5ea74f3d.png)
